import express from 'express';
import departmentRoutes from './department/department.js';
import imageRoutes from './image/image.js';
import medicineRoutes from './medicine/medicine.js';
import prescriptionRoutes from './prescription/prescription.js';
import doctorRoutes from './doctor/doctor.js';
import userRoutes from './user/user.js';
import appointmentRoutes from './appointment/appointment.js';
import slotRoutes from './slot/slot.js';
import orderRoutes from './order/order.js';
const router = express.Router();
router.use('/department', departmentRoutes);
router.use('/upload', imageRoutes);
router.use('/doctor', doctorRoutes);
router.use('/medicine', medicineRoutes);
router.use('/prescription', prescriptionRoutes);
router.use('/user', userRoutes);
router.use('/appointment', appointmentRoutes);
router.use('/slot', slotRoutes);
router.use('/order', orderRoutes);

export default router;
